on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  DEFAULT_PYTHON: "3.12"
    
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write 
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up uv
      run: pipx install uv

    - name: Set up Python ${{ env.DEFAULT_PYTHON }}
      id: python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}
        cache: "uv"

    - name: Install dependencies
      run: |
        uv pip install -r pyproject.toml --extra dev

    - name: Run pytest
      run: uv run pytest --cov pylamarzocco tests
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Set package version
      run: |
        version="${{ github.event.release.tag_name }}"
        version="${version,,}"
        version="${version#v}"
        poetry version --no-interaction "${version}"

    - name: Build package
      run: poetry build --no-interaction
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
